-- CreateTable
CREATE TABLE `DeliveryPricing` (
    `id` VARCHAR(191) NOT NULL,
    `under1Km` INTEGER NOT NULL DEFAULT 0,
    `km1To1_5` INTEGER NOT NULL DEFAULT 0,
    `km1_5To2` INTEGER NOT NULL DEFAULT 0,
    `km2To2_5` INTEGER NOT NULL DEFAULT 0,
    `km2_5To3` INTEGER NOT NULL DEFAULT 0,
    `above3PerKm` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
