-- AlterTable
ALTER TABLE `customerorder` ADD COLUMN `dropoffRegion` ENUM('KAMPUS_SUTOMO', 'KAMPUS_TUNTUNGAN', 'KAMPUS_PANCING', 'WILAYAH_LAINNYA') NULL,
    ADD COLUMN `pickupRegion` ENUM('KAMPUS_SUTOMO', 'KAMPUS_TUNTUNGAN', 'KAMPUS_PANCING', 'WILAYAH_LAINNYA') NULL;
